/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Tue May 30 16:48:11 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_finalbbcar_h_)
#define _finalbbcar_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief bbcarService identifiers */
enum _bbcarService_ids
{
    kbbcarService_service_id = 1,
    kbbcarService_bbcar_start_id = 1,
    kbbcarService_bbcar_speed_id = 2,
    kbbcarService_bbcar_distance_id = 3,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name bbcarService
//@{
void bbcar_start(void);

float bbcar_speed(void);

float bbcar_distance(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _finalbbcar_h_
